env:
  browser: true
  commonjs: true
  es2021: true
extends: standard
parserOptions:
  ecmaVersion: latest
rules:
  {
    semi: [2, "always"],
    quotes: [2, "double"],
    indent: "off",
    space-before-function-paren: "off",
  }
